builds:
  - main: main.go
    binary: timer
    goos:
      - linux
      - darwin
      - windows
      - freebsd
      - netbsd
      - openbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
      - Releasing

archive:
  format: tgz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    darwin: macosx
    386: i386
    amd64: x86_64
  files:
      - LICENSE.md
      - README.md
