builds:
  - main: main.go
    binary: timer
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      # - 386
      - amd64
checksum:
  name_template: 'checksums_linux.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
      - Merge tag
      - Releasing

archive:
  format: tgz
  replacements:
    386: i386
    amd64: x86_64
  files:
      - LICENSE.md
      - README.md
