language: go
go:
  - 1.10.x
  - master
  - tip
os:
  - linux
  - osx
sudo: false
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libasound2-dev ; fi
install:
  - go get -v golang.org/x/tools/cmd/stringer
  - go get -v github.com/golang/dep/cmd/dep
  - "$HOME/gopath/bin/dep ensure -v -vendor-only"
script:
  - make
  - ./timer 3s -m
