language: go
go:
  - "1.x"
  - master
os:
  - linux
  - osx
sudo: false

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libasound2-dev ; fi
  - go get -v golang.org/x/tools/cmd/stringer
  # - go get -v github.com/golang/dep/cmd/dep
  # - "$HOME/gopath/bin/dep ensure -v -vendor-only"

script:
  - make
  - ./timer 3s -m
  - make clean

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  # From https://stackoverflow.com/a/8514318
  script: curl -sL https://git.io/goreleaser | bash -s - -f .goreleaser_linux.yml --rm-dist
  on:
    tags: true
    condition: 
      - $TRAVIS_OS_NAME = linux
      - $TRAVIS_GO_VERSION =~ ^1\.[0-9]+\.[0-9]+$
- provider: script
  skip_cleanup: true
  # From https://stackoverflow.com/a/8514318
  script: curl -sL https://git.io/goreleaser | bash -s - -f .goreleaser_darwin.yml --rm-dist
  on:
    tags: true
    condition: 
      - $TRAVIS_OS_NAME = osx
      - $TRAVIS_GO_VERSION =~ ^1\.[0-9]+\.[0-9]+$
- provider: script
  skip_cleanup: true
  # From https://stackoverflow.com/a/8514318
  script: curl -sL https://git.io/goreleaser | bash -s - -f .goreleaser_windows.yml --rm-dist
  on:
    tags: true
    condition: 
      - $TRAVIS_OS_NAME = osx
      - $TRAVIS_GO_VERSION =~ ^1\.[0-9]+\.[0-9]+$

notifications:
  email: false
